### ISSUE TITLE
Slim error

### ISSUE THREAD

**Issue by mohitbisht578** [lvonk/example-fitnesse-ruby-slim#2]
I am facing this error - (Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client) 
Can any you please provide me solution how you fix this
What to change in environment variable or eclipse 
As I think need to change classpath in environment variable and eclipse should be same?
Can you please help me out?

**Comment by lvonk** [comment]
Hi sorry, I am not using this anymore, so can't really help you.
